// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3Nds5g5nm9G2HQKQBDmHMNsSEbuJLWM',
    appId: '1:50759975888:web:50271aa34a854c4ff1afd5',
    messagingSenderId: '50759975888',
    projectId: 'phoneauth-d70d4',
    authDomain: 'phoneauth-d70d4.firebaseapp.com',
    storageBucket: 'phoneauth-d70d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrK_iUxu9TvP-h5l-SoQrad53hCfXrk8s',
    appId: '1:50759975888:android:08a0a77d05f71a44f1afd5',
    messagingSenderId: '50759975888',
    projectId: 'phoneauth-d70d4',
    storageBucket: 'phoneauth-d70d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJW-_ujgh245CCMI2K49ZsD_JORQayWno',
    appId: '1:50759975888:ios:ef7fdef805bbedb1f1afd5',
    messagingSenderId: '50759975888',
    projectId: 'phoneauth-d70d4',
    storageBucket: 'phoneauth-d70d4.appspot.com',
    androidClientId: '50759975888-7946c24hn66lueioe7vsp3b13t05404k.apps.googleusercontent.com',
    iosClientId: '50759975888-re5tgd7l5fjcbpa1t9va5r4rl20m1uvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJW-_ujgh245CCMI2K49ZsD_JORQayWno',
    appId: '1:50759975888:ios:ef7fdef805bbedb1f1afd5',
    messagingSenderId: '50759975888',
    projectId: 'phoneauth-d70d4',
    storageBucket: 'phoneauth-d70d4.appspot.com',
    androidClientId: '50759975888-7946c24hn66lueioe7vsp3b13t05404k.apps.googleusercontent.com',
    iosClientId: '50759975888-re5tgd7l5fjcbpa1t9va5r4rl20m1uvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneapp',
  );
}
